version: '3.8'

services:
  magnetico:
    image: ghcr.io/datagram1/magnetico:latest
    container_name: magnetico
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-magnetico}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-magnetico}?sslmode=disable
      - ADDR=${MAGNETICO_ADDR:-0.0.0.0:8080}
      - MAX_RPS=${MAGNETICO_MAX_RPS:-500}
      - LEECH_MAX_N=${MAGNETICO_LEECH_MAX_N:-1000}
    volumes:
      - magnetico_data:/data
      - magnetico_config:/config
    ports:
      - "8080:8080"
      - "${DHT_PORT:-6881}:6881/udp"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - magnetico-network

  nginx:
    image: nginx:alpine
    container_name: magnetico-nginx
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - magnetico
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - magnetico-network

  postgres:
    image: postgres:15-alpine
    container_name: magnetico-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-magnetico}
      - POSTGRES_USER=${POSTGRES_USER:-magnetico}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-magnetico} -d ${POSTGRES_DB:-magnetico}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - magnetico-network

volumes:
  magnetico_data:
    driver: local
  magnetico_config:
    driver: local
  postgres_data:
    driver: local

networks:
  magnetico-network:
    driver: bridge
    name: magnetico-network
